// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Gs81C8skF1I6eBtlGcNZxhAqMdUGxlY',
    appId: '1:551468081879:web:a6ac2e39df34a4af3a4692',
    messagingSenderId: '551468081879',
    projectId: 'joga-mais-fb74e',
    authDomain: 'joga-mais-fb74e.firebaseapp.com',
    storageBucket: 'joga-mais-fb74e.firebasestorage.app',
    measurementId: 'G-2H8DFCTJJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_Tl3sFCnYaHEOA2kvSupGt3oDj1qR90',
    appId: '1:551468081879:android:cf54d8ff94707ea23a4692',
    messagingSenderId: '551468081879',
    projectId: 'joga-mais-fb74e',
    storageBucket: 'joga-mais-fb74e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYOPVda9NLMZtyQIDpsC14lfqO42BiqQQ',
    appId: '1:551468081879:ios:eb1eb3113422b0cc3a4692',
    messagingSenderId: '551468081879',
    projectId: 'joga-mais-fb74e',
    storageBucket: 'joga-mais-fb74e.firebasestorage.app',
    iosClientId: '551468081879-7g0ihrua3th2qps2r2nr74pn7idil4sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYOPVda9NLMZtyQIDpsC14lfqO42BiqQQ',
    appId: '1:551468081879:ios:eb1eb3113422b0cc3a4692',
    messagingSenderId: '551468081879',
    projectId: 'joga-mais-fb74e',
    storageBucket: 'joga-mais-fb74e.firebasestorage.app',
    iosClientId: '551468081879-7g0ihrua3th2qps2r2nr74pn7idil4sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Gs81C8skF1I6eBtlGcNZxhAqMdUGxlY',
    appId: '1:551468081879:web:2db5dee9aa7adc563a4692',
    messagingSenderId: '551468081879',
    projectId: 'joga-mais-fb74e',
    authDomain: 'joga-mais-fb74e.firebaseapp.com',
    storageBucket: 'joga-mais-fb74e.firebasestorage.app',
    measurementId: 'G-45ZT5J57YR',
  );
}
